### ISSUE TITLE
issue closed as 'not planned' .. but it was a bug

### ISSUE THREAD

**Issue by bcoca** [ansible/ansibotmini#3]
https://github.com/ansible/ansible/issues/81609
closing was fine, since it was for diff repo, but 'not planned' seems to be the wrong label

**Comment by mkrizek** [comment]
Closing as working as intended. The bot closes all issues (`waiting_on_contributor`, `needs_info` and "redirecting to collections repo") as "not planned", as in "not planned in this repository".
