### ISSUE TITLE
[TODO] Make Sentry version-aware

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansibotmini#6]
Old bot example: https://github.com/ansible/ansibullbot/blob/4d7ff8d/ansibullbot/constants.py#L456-L464 / https://github.com/ansible/ansibullbot/blob/4d7ff8d/ansibullbot/utils/sentry.py#L11.

The currently set constant version does not allow Sentry to make release-based observations or link the exact GitHub-hosted source code from the dashboard: https://github.com/ansible/ansibotmini/blob/18485e0/ansibotmini.py#L2093.

**Comment by mkrizek** [comment]
Fixed in https://github.com/ansible/ansibotmini/commit/13c0df555bb4a0d05e2dadb08ab25f6be607c2a4
